import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";
import type { AuditReport, DevelopmentPlanItem, Finding, MaturityScore } from "@codex-product-dogfood/schemas";
import { countFindings } from "@codex-product-dogfood/schemas";

export function scoreMaturity(findings: Finding[]): MaturityScore {
  const counts = countFindings(findings);
  const score = Math.max(0, 100 - counts.P0 * 35 - counts.P1 * 15 - counts.P2 * 5);
  const releaseReadiness = counts.P0 > 0 ? "blocked" : counts.P1 > 2 ? "needs-work" : score >= 85 ? "strong" : "usable";
  const rationale = [
    `${counts.P0} P0, ${counts.P1} P1, ${counts.P2} P2 findings`,
    releaseReadiness === "blocked"
      ? "Release is blocked by at least one critical user journey failure."
      : "No critical blocker was detected by the MVP heuristics."
  ];
  return { score, releaseReadiness, rationale };
}

export function buildDevelopmentPlan(findings: Finding[]): DevelopmentPlanItem[] {
  return findings
    .slice()
    .sort((a, b) => severityRank(a.severity) - severityRank(b.severity))
    .map((finding) => ({
      priority: finding.severity,
      title: finding.title,
      rationale: `${finding.userSymptom} Actual behavior: ${finding.actual}`,
      acceptanceCriteria: finding.acceptanceCriteria
    }));
}

export async function writeReport(outDir: string, report: AuditReport): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(`${outDir}/findings.json`, `${JSON.stringify(report, null, 2)}\n`);
  await writeFile(`${outDir}/report.md`, renderMarkdownReport(outDir, report));
}

export function renderMarkdownReport(outDir: string, report: AuditReport): string {
  const { summary, findings, developmentPlan } = report;
  const lines: string[] = [];
  lines.push("# Product Dogfood Report");
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`- URL: ${summary.url}`);
  lines.push(`- Profile: ${summary.profile}`);
  lines.push(`- Generated: ${summary.generatedAt}`);
  lines.push(`- Viewports: ${summary.viewports.join(", ")}`);
  lines.push(`- Maturity score: ${summary.maturity.score}/100`);
  lines.push(`- Release readiness: ${summary.maturity.releaseReadiness}`);
  lines.push(`- Finding counts: P0 ${summary.findingCounts.P0}, P1 ${summary.findingCounts.P1}, P2 ${summary.findingCounts.P2}`);
  lines.push(`- Top risk: ${topRisk(findings)}`);
  lines.push("");
  lines.push("## Maturity Rationale");
  lines.push("");
  for (const item of summary.maturity.rationale) {
    lines.push(`- ${item}`);
  }
  lines.push("");
  lines.push("## Findings By Priority");
  lines.push("");
  if (findings.length === 0) {
    lines.push("No findings were generated by the MVP heuristics. Review screenshots manually before treating this as a clean release.");
  } else {
    for (const severity of ["P0", "P1", "P2"] as const) {
      const severityFindings = findings.filter((finding) => finding.severity === severity);
      if (severityFindings.length === 0) {
        continue;
      }
      lines.push(`### ${severity}`);
      lines.push("");
      severityFindings.forEach((finding, index) => {
        lines.push(`#### ${index + 1}. ${finding.title}`);
        lines.push("");
        lines.push(`- Journey: ${finding.journey}`);
        lines.push(`- Viewport: ${finding.viewport}`);
        if (finding.introducedAtStep) {
          lines.push(`- Introduced at step: ${finding.introducedAtStep.index}. ${finding.introducedAtStep.label} (${finding.introducedAtStep.action})`);
        }
        if (finding.introducedAtEvent) {
          const event = finding.introducedAtEvent;
          const eventStep = event.stepIndex && event.stepLabel ? ` in step ${event.stepIndex}. ${event.stepLabel}` : "";
          lines.push(`- Introduced at event: ${event.event}${event.elapsedMs ? ` (${event.elapsedMs}ms)` : ""}${eventStep}`);
          if (event.screenshot) {
            lines.push(`- Introduced screenshot: ${relative(dirname(`${outDir}/report.md`), event.screenshot)}`);
          }
          if (event.bboxPath) {
            lines.push(`- Introduced bbox: ${relative(dirname(`${outDir}/report.md`), event.bboxPath)}`);
          }
          if (event.domPath) {
            lines.push(`- Introduced DOM: ${relative(dirname(`${outDir}/report.md`), event.domPath)}`);
          }
          const domSummary = summarizeIntroducedEventDom(event.domSummary);
          if (domSummary) {
            lines.push(`- Introduced DOM summary: ${domSummary}`);
          }
          if (event.consoleSummary) {
            lines.push(`- Console near event: ${event.consoleSummary.count}${event.consoleSummary.latest.length ? ` (${event.consoleSummary.latest.slice(-3).join(" | ")})` : ""}`);
          }
          if (event.networkSummary) {
            lines.push(`- Network near event: ${event.networkSummary.count}${event.networkSummary.latest.length ? ` (${event.networkSummary.latest.slice(-3).join(" | ")})` : ""}`);
          }
        }
        if (finding.confidence) {
          lines.push(`- Confidence: ${finding.confidence}`);
        }
        if (finding.tags?.length) {
          lines.push(`- Tags: ${finding.tags.join(", ")}`);
        }
        lines.push(`- User symptom: ${finding.userSymptom}`);
        lines.push(`- Expected: ${finding.expected}`);
        lines.push(`- Actual: ${finding.actual}`);
        lines.push("- Evidence:");
        for (const evidence of finding.evidence) {
          const evidencePath = evidence.path ? ` (${relative(dirname(`${outDir}/report.md`), evidence.path)})` : "";
          lines.push(`  - ${evidence.type}: ${evidence.detail}${evidencePath}`);
        }
        lines.push("- Repro steps:");
        finding.reproSteps.forEach((step) => lines.push(`  - ${step}`));
        lines.push("- Acceptance criteria:");
        finding.acceptanceCriteria.forEach((criterion) => lines.push(`  - ${criterion}`));
        lines.push("");
      });
    }
  }
  lines.push("## Recommended Development Plan");
  lines.push("");
  if (developmentPlan.length === 0) {
    lines.push("No plan items were generated. Do a manual screenshot review and add targeted journey checks before launch.");
  } else {
    const buckets = [
      { title: "Now", priorities: ["P0"] },
      { title: "Next", priorities: ["P1"] },
      { title: "Later", priorities: ["P2"] }
    ];
    for (const bucket of buckets) {
      const items = developmentPlan.filter((item) => bucket.priorities.includes(item.priority));
      if (!items.length) {
        continue;
      }
      lines.push(`### ${bucket.title}`);
      lines.push("");
      items.forEach((item, index) => {
        lines.push(`${index + 1}. [${item.priority}] ${item.title}`);
        lines.push(`   - Why: ${item.rationale}`);
        lines.push(`   - Acceptance: ${item.acceptanceCriteria.join("; ")}`);
      });
      lines.push("");
    }
  }
  lines.push("## Manual Review Checklist");
  lines.push("");
  lines.push("- Review every screenshot linked from P0/P1 findings.");
  lines.push("- Review `timeline/contact-sheet.html`, `timeline.json`, and per-step timeline manifests for upload, send, streaming formula, Markdown table, and composer/status state sequences.");
  lines.push("- Mark heuristic-only missing-signal findings as confirmed or false positive.");
  lines.push("- Check mobile and small-mobile screenshots for blocked primary actions.");
  lines.push("- Check bbox/overflow findings for composer, upload, voice, send, and status elements shifted outside the viewport.");
  lines.push("- Convert confirmed P0/P1 findings into implementation tasks before release.");
  lines.push("");
  lines.push("## Evidence Inventory");
  lines.push("");
  lines.push("- Timeline contact sheet: `timeline/contact-sheet.html`");
  lines.push("- Timeline manifest: `timeline.json`");
  lines.push("- Per-step timeline manifests: `timeline/<viewport>/<journey>/<step>/manifest.json`");
  const screenshots = new Set<string>();
  for (const finding of findings) {
    for (const evidence of finding.evidence) {
      if (evidence.type === "screenshot" && evidence.path) {
        screenshots.add(relative(dirname(`${outDir}/report.md`), evidence.path));
      }
    }
  }
  if (screenshots.size === 0) {
    lines.push("- See `screenshots/` for captured viewport evidence.");
  } else {
    for (const screenshot of screenshots) {
      lines.push(`- ${screenshot}`);
    }
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function summarizeIntroducedEventDom(domSummary: Record<string, boolean | number | string | string[]> | undefined): string | undefined {
  if (!domSummary || typeof domSummary !== "object") {
    return undefined;
  }
  const summary = domSummary as Record<string, boolean | number | string | string[]>;
  const parts: string[] = [];
  if (Array.isArray(summary.statusTexts) && summary.statusTexts.length) {
    parts.push(`status="${summary.statusTexts.slice(0, 3).join(" | ")}"`);
  }
  if (typeof summary.visibleImages === "number") {
    parts.push(`visibleImages=${summary.visibleImages}`);
  }
  if (Array.isArray(summary.imageSummaries) && summary.imageSummaries.length) {
    parts.push(`images=${summary.imageSummaries.slice(0, 2).join(" | ")}`);
  }
  if (typeof summary.rawLatexMatches === "number") {
    parts.push(`rawLatexMatches=${summary.rawLatexMatches}`);
  }
  if (typeof summary.scrollWidth === "number" && typeof summary.clientWidth === "number") {
    parts.push(`scroll/client=${summary.scrollWidth}/${summary.clientWidth}`);
  }
  return parts.join("; ") || undefined;
}

function severityRank(severity: Finding["severity"]): number {
  return severity === "P0" ? 0 : severity === "P1" ? 1 : 2;
}

function topRisk(findings: Finding[]): string {
  if (findings.some((finding) => finding.severity === "P0")) {
    return "Critical journey blocker detected.";
  }
  if (findings.some((finding) => finding.severity === "P1")) {
    return "Core journey risk needs product review.";
  }
  if (findings.some((finding) => finding.severity === "P2")) {
    return "No blocker detected, but polish gaps remain.";
  }
  return "No automated findings; manual screenshot review still recommended.";
}
