import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";
import type { AuditReport, DevelopmentPlanItem, Finding, MaturityScore } from "@codex-product-dogfood/schemas";
import { countFindings } from "@codex-product-dogfood/schemas";

export function scoreMaturity(findings: Finding[]): MaturityScore {
  const counts = countFindings(findings);
  const score = Math.max(0, 100 - counts.P0 * 35 - counts.P1 * 15 - counts.P2 * 5);
  const releaseReadiness = counts.P0 > 0 ? "blocked" : counts.P1 > 2 ? "needs-work" : score >= 85 ? "strong" : "usable";
  const rationale = [
    `${counts.P0} P0, ${counts.P1} P1, ${counts.P2} P2 findings`,
    releaseReadiness === "blocked"
      ? "Release is blocked by at least one critical user journey failure."
      : "No critical blocker was detected by the MVP heuristics."
  ];
  return { score, releaseReadiness, rationale };
}

export function buildDevelopmentPlan(findings: Finding[]): DevelopmentPlanItem[] {
  return findings
    .slice()
    .sort((a, b) => severityRank(a.severity) - severityRank(b.severity))
    .map((finding) => ({
      priority: finding.severity,
      title: finding.title,
      rationale: `${finding.userSymptom} Actual behavior: ${finding.actual}`,
      acceptanceCriteria: finding.acceptanceCriteria
    }));
}

export async function writeReport(outDir: string, report: AuditReport): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(`${outDir}/findings.json`, `${JSON.stringify(report, null, 2)}\n`);
  await writeFile(`${outDir}/report.md`, renderMarkdownReport(outDir, report));
}

export function renderMarkdownReport(outDir: string, report: AuditReport): string {
  const { summary, findings, developmentPlan } = report;
  const lines: string[] = [];
  lines.push("# Product Dogfood Report");
  lines.push("");
  lines.push(`- URL: ${summary.url}`);
  lines.push(`- Profile: ${summary.profile}`);
  lines.push(`- Generated: ${summary.generatedAt}`);
  lines.push(`- Viewports: ${summary.viewports.join(", ")}`);
  lines.push(`- Maturity score: ${summary.maturity.score}/100`);
  lines.push(`- Release readiness: ${summary.maturity.releaseReadiness}`);
  lines.push(`- Finding counts: P0 ${summary.findingCounts.P0}, P1 ${summary.findingCounts.P1}, P2 ${summary.findingCounts.P2}`);
  lines.push("");
  lines.push("## Maturity Rationale");
  lines.push("");
  for (const item of summary.maturity.rationale) {
    lines.push(`- ${item}`);
  }
  lines.push("");
  lines.push("## Findings");
  lines.push("");
  if (findings.length === 0) {
    lines.push("No findings were generated by the MVP heuristics. Review screenshots manually before treating this as a clean release.");
  } else {
    findings.forEach((finding, index) => {
      lines.push(`### ${index + 1}. [${finding.severity}] ${finding.title}`);
      lines.push("");
      lines.push(`- Journey: ${finding.journey}`);
      lines.push(`- Viewport: ${finding.viewport}`);
      lines.push(`- User symptom: ${finding.userSymptom}`);
      lines.push(`- Expected: ${finding.expected}`);
      lines.push(`- Actual: ${finding.actual}`);
      lines.push("- Evidence:");
      for (const evidence of finding.evidence) {
        const evidencePath = evidence.path ? ` (${relative(dirname(`${outDir}/report.md`), evidence.path)})` : "";
        lines.push(`  - ${evidence.type}: ${evidence.detail}${evidencePath}`);
      }
      lines.push("- Repro steps:");
      finding.reproSteps.forEach((step) => lines.push(`  - ${step}`));
      lines.push("- Acceptance criteria:");
      finding.acceptanceCriteria.forEach((criterion) => lines.push(`  - ${criterion}`));
      lines.push("");
    });
  }
  lines.push("## Recommended Development Plan");
  lines.push("");
  if (developmentPlan.length === 0) {
    lines.push("No plan items were generated. Do a manual screenshot review and add targeted journey checks before launch.");
  } else {
    developmentPlan.forEach((item, index) => {
      lines.push(`${index + 1}. [${item.priority}] ${item.title}`);
      lines.push(`   - Why: ${item.rationale}`);
      lines.push(`   - Acceptance: ${item.acceptanceCriteria.join("; ")}`);
    });
  }
  lines.push("");
  lines.push("## Evidence Inventory");
  lines.push("");
  const screenshots = new Set<string>();
  for (const finding of findings) {
    for (const evidence of finding.evidence) {
      if (evidence.type === "screenshot" && evidence.path) {
        screenshots.add(relative(dirname(`${outDir}/report.md`), evidence.path));
      }
    }
  }
  if (screenshots.size === 0) {
    lines.push("- See `screenshots/` for captured viewport evidence.");
  } else {
    for (const screenshot of screenshots) {
      lines.push(`- ${screenshot}`);
    }
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function severityRank(severity: Finding["severity"]): number {
  return severity === "P0" ? 0 : severity === "P1" ? 1 : 2;
}
